config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  mount Ckeditor::Engine => '/ckeditor'
	root to: 'categories#index'
	resources :categories
	resources :articles do
		resources :comments
	end
	resources :tags
	resources :authors do
		resources :users
	end
	resources :author_sessions, only: [ :new, :create, :destroy ]
	resources :password_resets

	get 'login' => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
	belongs_to :category
	belongs_to :author
	validates :category, presence: true
	has_many :comments, dependent: :destroy
	has_many :taggings
	has_many :tags, through: :taggings, dependent: :destroy
	has_many :attachments, dependent: :destroy
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
def tag_list
	tags.join(", ")
end
def tag_list=(tags_string)
	tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
	new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
	self.tags = new_or_found_tags
end
  def to_param
    [title.parameterize].join("-")
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
include ArticlesHelper

 before_action :require_login, except: [:index, :show]
 before_action :require_permission, only: [:edit, :destroy]

def require_permission
 unless current_user.try(:admin?) || current_user == Article.find(params[:id]).author 
 	redirect_to root_path
    flash.notice = "You Can't Delete or Edit This Article as you are not the Author."
    
  end
end

def index
  @articles = Article.all.order(created_at: :desc)
  
  @articles_by_month = Article.all.order(created_at: :desc).group_by { |article| article.created_at.beginning_of_month }
end
def show
	@article = Article.friendly.find(params[:id])
	@comment = Comment.new
	@comment.article_id = @article_id
	@article_author = Article.includes(:author).friendly.find(params[:id])[:author_id]
end
def new
	@article = Article.new
	@tags = Tag.all.map {|t| [t.name] }
	@categories = Category.all
	respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @article }
    end

end
def create
	@article = Article.new(article_params)
	@article.category.name = params[:category_id]
	@article.author = current_user
	@article.save
	flash.notice = "Article '#{@article.title}' has Been Created."	

	redirect_to action: "index"
end
def destroy
	@article = Article.find(params[:id])
	@article.destroy
	@articles = Article.all
	

	flash.notice = "Article Deleted"

	redirect_to action: "index" 
end
def edit
	@article = Article.find(params[:id])
	@tags = Tag.all.map {|t| [t.name] }
	@categories = Category.all


end
def update
	@article = Article.find(params[:id])
	@article.update(article_params)

	flash.notice = "Your Article has Been Updated"

	redirect_to article_path(@article)
end
end

app/helpers/articles_helper.rb
module ArticlesHelper
def article_params
	params.require(:article).permit(:title, :body, :tag_list, :category_id, :author_id)
end
end

app/views/articles/_comment.html.erb
<div>
	<h4>Comment by <%= comment.author_name %></h4>
	<p class="comment"><%= comment.body %></p>
	<p> <%= distance_of_time_in_words(Time.now , comment.created_at) %> ago</p>
</div>

app/views/articles/_form.html.erb
<%= form_for (@article), html: {multipart: true} do |f| %>

	<ul>
	<% @article.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
	</ul>
	<p>
		<%= f.label :title %> <br/>
		<%= f.text_field :title %>
	</p>
	<p>
		<%= f.label :body %><br />
		<%= f.cktext_area :body %>
	</p>
	<p>
		<%= f.label :tag_list %> <br>
		<%= f.text_field :tag_list %>
	</p>
	<p>
		<%=f.label :Category %><br>
		<%= collection_select(:article, :category_id, @categories, :id, :name, {:prompt => "Select One" })%>
	</p>
	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/articles/_nav.html.erb
<div class="blogname">
<h1>Jogoo letters</h1>
<h5 id="catch">My Head in my Fingers</h5>
</div>
<ul>
	<li>
		<%= link_to "Home", root_path %>
		<%= link_to "All articles", articles_path %>
		<%= link_to "Tags", tags_path %>
		<% if logged_in? %>
		<%= link_to "Authors", authors_path %>
    	<% end %>
    </li>
 </ul>

app/views/articles/edit.html.erb
<div class="wrapper"><h1>Edit Article.</h1></div>
<%= render partial: 'form' %>

app/views/articles/index.html.erb
<script type="text/coffeescript">$('.list > li a').click ->
  $(this).parent().find('ul').toggle()
  return
</script>
<div class="wrapper"><h1>All Articles</h1></div>
<div class="articles-list">
<% if logged_in? %>
<%= link_to "Create A New Article", new_article_path, class: "new_article" %>
<% end %>
<ul id='articles'>
	<% @articles.each do |article| %>
		<li>
      <div id="article-holder">
         <div id="article-holder-header"><h4><%= link_to "#{article.title}", article_path(article)%></h4></div>
      <div class="article-holder">
        <p><%= simple_format article.body %></p>
      </div>
      <div class="show-more">
			<%= link_to 'Show more', article_path(article) %>
    </div>
  </div>
		</li>
	<% end %>
</ul>
</div>
  <% if logged_in? %>
      <div id="post-archive">
      <h3>Article archive</h3>

      <ul class="list">
      <% @articles_by_month.each do |month, articles| %>

        <li>
       <a><%="#{month.strftime('%B %Y')} (#{articles.count}):" %></a>
        <ul>
            <% for article in articles %>
          
           <li><%= link_to article.title, article_path(article) %></li>
           
         <% end %>
          </ul>
       </li>

      <% end %>
       </ul>
      </div>
  <% end %>

app/views/articles/new.html.erb
<div class="content">
<div class="wrapper"><h1>Create a New Article</h1></div>
<%= render partial: 'form' %>
</div>

app/views/articles/show.html.erb
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = 'https://connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10';
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>
<% set_meta_tags description: @article.body.truncate_words(17),
                 keywords: @article.title.split(/\W+/), 
                 url: article_url(@article),
                 site: "www.jogooletters.com" 
                 %>
<div class="article">
	<div class="article_show">
		<h1 class ="article_header"><%=title @article.title %></h1>
	</div>
	<div class="beta-inner">
		<div class= "article-content" >
			<div class="article-image" style='height: 100%; width: 95%; object-fit: contain'>
				<% if @article.image.exists? %>
					<%= image_tag @article.image.url, class: 'article_image' %><br>
				<% end %>
			</div>
			<p><%= @article.body.html_safe %></p>


			<p class="article-time">
				<%= @article.created_at.strftime("%B %d %Y, %l:%M%P") %><br>
				<% unless @article.author.blank? %>
					by <%= link_to "#{@article.author.username}", author_path(@article_author)%>
				<% end %> 
			</p>

			<p id='tags'>
				Tags:
				<% @article.tags.each do |tag| %>
				<div class="tags">
					<%= link_to tag.name, tag_path(tag) %>
				</div>
				<% end %>
			</p>
			<div class="article-comment">
				<!--<%= render partial: 'articles/comment' , collection: @article.comments %>
				<%= render partial: 'comments/form' %>-->
				<div class="fb-comments" data-numposts="5"></div>

			</div>

			<% if current_user.try(:admin?) || current_user == Article.friendly.find(params[:id]).author %>
			<%= link_to "Delete Article", article_path(@article), method: :delete, data: {confirm: "Do you want to delete the article?"}, id: 'article-show-link' %>
			<%= link_to "Edit Article", edit_article_path(@article), id: 'article-show-link' %>
			<% end %>
			<div class="share_icons">
				<!--<div class="social-share-button fb-follow">
			    <a class="ssb-icon ssb-facebook" href="https://www.facebook.com/sharer/sharer.php?" target="popup" onclick="window.open('https://www.facebook.com/sharer/sharer.php?','popup','width=555,height=400'); return false;"></a></div>
			    <%= social_share_button_tag(@article.title, :url => "http://myapp.com/foo/bar", :image => "http://foo.bar/images/a.jpg", desc: "The summary of page", via: "MyTwitterName") %>-->
			    <!-- Go to www.addthis.com/dashboard to customize your tools --> <div class="addthis_inline_share_toolbox"></div>
							
			</div>
			<%= link_to "<<Back to Articles List", articles_path %><br>
		</div>
	</div>

			  
</div>
​<script type="text/javascript">
var addthis_config = addthis_config||{};
    addthis_config.data_track_addressbar = false;
    addthis_config.data_track_clickback = false;
</script>

<!-- Go to www.addthis.com/dashboard to customize your tools --> <script type="text/javascript" src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-5a079d6e1bd51e5e"></script> 