config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  mount Ckeditor::Engine => '/ckeditor'
	root to: 'categories#index'
	resources :categories
	resources :articles do
		resources :comments
	end
	resources :tags
	resources :authors do
		resources :users
	end
	resources :author_sessions, only: [ :new, :create, :destroy ]
	resources :password_resets

	get 'login' => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  has_one :user, dependent: :destroy
  has_many :articles, dependent: :nullify
 	
 
	def to_s
		name
	end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :zero_authors_or_authenticated, only: [:new, :create]
  before_action :require_login, except: [:show, :new, :create]
  before_action :admin_only, only: :index
  # GET /authors
  # GET /authors.json
  def zero_authors_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false      
      end
   end
  def admin_only
    unless current_user.try(:admin?)      
    redirect_to root_path     
    end
  end
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  @author = Author.find(params[:id]) 
  @author = Author.includes(:user).find(params[:id])
   @user = @author.user
   @users = User.new
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy

  flash.notice = "Author Deleted"

  redirect_to  action: "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper

def name_for(author)
	author.user.body if author.user.present?
end

end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true) do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :username %><br>
    <%= form.text_field :username, id: :author_username %>
  </div>

  <div class="field">
    <%= form.label :email %><br>
    <%= form.text_field :email, id: :author_email %>
  </div>

  <div class="field">
    <%= form.label :password %><br>
    <%= form.password_field :password, id: :author_password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %><br>
    <%= form.password_field :password_confirmation, id: :author_password_confirmation %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/authors/_user.html.erb
<div>
	<%= user.body %>
	
</div>

app/views/authors/edit.html.erb
<div class="wrapper"><h1>Editing Author</h1></div>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<div class="wrapper"><h1>Authors</h1></div>
<div class="article-content">
<div>
<ul class="authors-list">
	<% @authors.each do |author| %>
		<li>
			<%= link_to author.username, author_path(author)%>
			
		</li>
	<% end %>
</ul>

</div>
<%= link_to 'New Author', new_author_path, class: "new-author" %>
</div>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Back', authors_path %>

app/views/authors/show.html.erb
<div class="author-profile">
	<div class="gravatar">
		<p><%= image_tag gravatar_url("#{@author.email}", 120), alt: "" %><p>
	</div>
	<div class="bio">
		<p><%= @author.username %></p><br>
 		<p><%= @author.email %></p>
 		<br>
   		<p>BIO:</p>
   		<p><%= name_for (@author) %></p>
   		<% if logged_in? %>
	   		<%if @author.user.blank? %>
	   			<%= render partial: 'users/form' %>

	   		<% end %>
	   		<%if current_user == @author %>
	   			<%= link_to "Edit ", edit_author_user_path(@user), id: 'article-show-link' %>
	   		<%end %>
	 	<% end %>
		<br>

	<% if current_user.try(:admin?) %>
		<%= link_to "delete", author_path(@author), method: :delete, data: {confirm: "Do you want to delete the author?"} %>
	<% end %>
	</div>
</div>