config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  mount Ckeditor::Engine => '/ckeditor'
	root to: 'categories#index'
	resources :categories
	resources :articles do
		resources :comments
	end
	resources :tags
	resources :authors do
		resources :users
	end
	resources :author_sessions, only: [ :new, :create, :destroy ]
	resources :password_resets

	get 'login' => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
	belongs_to :category
	belongs_to :author
	validates :category, presence: true
	has_many :comments, dependent: :destroy
	has_many :taggings
	has_many :tags, through: :taggings, dependent: :destroy
	has_many :attachments, dependent: :destroy
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
def tag_list
	tags.join(", ")
end
def tag_list=(tags_string)
	tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
	new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
	self.tags = new_or_found_tags
end
  def to_param
    [title.parameterize].join("-")
  end

end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :article
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  has_one :user, dependent: :destroy
  has_many :articles, dependent: :nullify
 	
 
	def to_s
		name
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles
def to_s
	name
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings

def to_s
	name
end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  belongs_to :author
  validates :author_id, presence: true

 def to_a
	
end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :zero_authors_or_authenticated, only: [:new, :create]
  before_action :require_login, except: [:show, :new, :create]
  before_action :admin_only, only: :index
  # GET /authors
  # GET /authors.json
  def zero_authors_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false      
      end
   end
  def admin_only
    unless current_user.try(:admin?)      
    redirect_to root_path     
    end
  end
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  @author = Author.find(params[:id]) 
  @author = Author.includes(:user).find(params[:id])
   @user = @author.user
   @users = User.new
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy

  flash.notice = "Author Deleted"

  redirect_to  action: "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
include CategoriesHelper

def show
	@category = Category.find(params[:id])

end

def index
  @categories = Category.all
 
  @articles = Article.order(created_at: :desc).limit(5)
  
end
def edit
	@category = Category.find(params[:id])
end

def new
	@category = Category.new
end
def create
	@category = Category.new(category_params)
	@category.save
	flash.notice = "Category '#{@category.name}' has Been Created."

	redirect_to categories_path
end
def destroy
	@category = Category.find(params[:id])
	@category.destroy
	@categories = Category.all
	

	flash.notice = "Category Deleted"

	redirect_to action: "index" 
end
def update
	@category = Category.find(params[:id])
	@category.update(category_params)

	flash.notice = "Your Category has Been Updated"

	redirect_to category_path(@category)
end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
def show
	@tag = Tag.find(params[:id])

end
def index
	@tags = Tag.all
end
def destroy
	@tag = Tag.find(params[:id])
	@tag.destroy
	@tags = Tag.all 
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 before_action :require_login, except: [:index]
	 before_action :require_owner, only: :edit
def require_owner
	if current_user != Author.includes(:user).find(params[:id])
    redirect_to root_path
    flash.notice = "You Cannot Edit This Profile"
    
  	end
end
def create
	@user = User.new(user_params)
	@user.author_id = params[:author_id]
	@user.save

	redirect_to root_path
end
def edit
	 @author = Author.includes(:user).find(params[:id])
	@user = @author.user
	
end
def update
	@user = User.find(params[:id])
	@user.author_id = params[:author_id]
	@user.update(user_params)

	flash.notice = "Your Profile has Been Updated"

   redirect_to author_path(@user)
end
def index
	@user = User.find(params[:author_id])
end

def user_params
	params.require(:user).permit(:body)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_url(email, size)
    	gravatar = Digest::MD5::hexdigest(email).downcase
    	url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
def article_params
	params.require(:article).permit(:title, :body, :tag_list, :category_id, :author_id)
end
end

app/helpers/author_sessions_helper.rb
module AuthorSessionsHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper

def name_for(author)
	author.user.body if author.user.present?
end

end

app/helpers/categories_helper.rb
module CategoriesHelper
def category_params
	params.require(:category).permit(:name)
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_form.html.erb
<%= form_for (@category) do |f| %>
<ul>
	<% @category.errors.full_messages.each do |error| %>
		<li><%= error %></li>
	<% end %>
</ul>
<p>
		<%= f.label :name %> <br/>
		<%= f.text_field :name %>
</p>
<p>
		<%= f.submit %>
</p>
<% end %>

app/views/categories/edit.html.erb
<div class="wrapper"><h1>Edit Category.</h1></div>
<%= render partial: 'form' %>

app/views/categories/index.html.erb
<div class="wrapper"><h1 id="inset">Categories</h1></div>
<div class="beta">
<!--<ul id='tags'>
	<% @categories.each do |category| %>
	<li>
		<%= link_to category.name, category_path(category), class: 'article_title', id: "category_#{category.id}" %>

	</li>
	<% end %>
	
</ul> -->
	<div id="category_4">
		<a class="home-link" id="category_4" href="/categories/4"><span id="category">Diary of a Kenyan</span></a><br>
	</div>


	<div id="category_2">
		<a class="home-link" id="category_2" href="/categories/2"><span id="category">Politics</span></a><br>
	</div>

	<div id="category_3">
		<a class="home-link" id="category_3" href="/categories/3"><span id="category">Narratives/ Fiction/ Fantasy</span></a><br>
	</div>
	<div id="category_1">
		<a class="home-link" id="category_1" href="/categories/1"><span id="category"> Poems</span></a><br>
	</div></a>
	
<% if logged_in? %>
<%= link_to "Create A New Category", new_category_path, class: 'new_category' %>
<% end %>
</div>
<div class="recent-articles"> 
	<div id="recent-articles">
	<h3>Recent articles</h3>
	<ul>
	<% @articles.each do |article| %>
		<li>
			<div class="textbox">
			<%= link_to article.title, article_path(article) %>
			</div>
		</li>
	<% end %>
	</ul>
	</div>
</div>  
<br>
<br>

app/views/categories/new.html.erb
<div class="wrapper"><h1>Create a New Category</h1></div>
<%= render partial: 'form' %>

app/views/categories/show.html.erb
<div class="wrapper"><h1> <%= @category.name %></h1></div>
<br>
<div id="category-articles" style="text-align: left;">
	<ul class="articles-list" id="articles">
		<% @category.articles.order(created_at: :desc).each do |article| %>
			<li>
				<div id="article-holder">
					 <div class="article-holder">
		        		<h4><%= article.title %></h4>
		       			 <p><%= simple_format article.body %></p>
		      		</div>
		      		<div class="show-more">
					<%= link_to 'Show more', article_path(article) %>
		    		</div>
				</div>
			</li>
		<% end %>
	</ul>
<!--<% if logged_in? %>
<%= link_to "delete", category_path(@category), method: :delete, data: {confirm: "Do you want to delete the category?"} %><br>
<%= link_to "edit", edit_category_path(@category), id: 'article-show-link' %>
<% end %>-->
</div>