config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

  mount Ckeditor::Engine => '/ckeditor'
	root to: 'categories#index'
	resources :categories
	resources :articles do
		resources :comments
	end
	resources :tags
	resources :authors do
		resources :users
	end
	resources :author_sessions, only: [ :new, :create, :destroy ]
	resources :password_resets

	get 'login' => 'author_sessions#new'
	get 'logout' => 'author_sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged
	belongs_to :category
	belongs_to :author
	validates :category, presence: true
	has_many :comments, dependent: :destroy
	has_many :taggings
	has_many :tags, through: :taggings, dependent: :destroy
	has_many :attachments, dependent: :destroy
	has_attached_file :image
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png"]
def tag_list
	tags.join(", ")
end
def tag_list=(tags_string)
	tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
	new_or_found_tags = tag_names.collect {|name| Tag.find_or_create_by(name: name)}
	self.tags = new_or_found_tags
end
  def to_param
    [title.parameterize].join("-")
  end

end

app/models/attachment.rb
class Attachment < ApplicationRecord
  belongs_to :article
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  has_one :user, dependent: :destroy
  has_many :articles, dependent: :nullify
 	
 
	def to_s
		name
	end
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :articles
def to_s
	name
end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
	has_many :taggings
	has_many :articles, through: :taggings

def to_s
	name
end
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :article
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!
  belongs_to :author
  validates :author_id, presence: true

 def to_a
	
end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  before_action :zero_authors_or_authenticated, only: [:new, :create]
  before_action :require_login, except: [:show, :new, :create]
  before_action :admin_only, only: :index
  # GET /authors
  # GET /authors.json
  def zero_authors_or_authenticated
      unless Author.count == 0 || current_user
        redirect_to root_path
        return false      
      end
   end
  def admin_only
    unless current_user.try(:admin?)      
    redirect_to root_path     
    end
  end
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  @author = Author.find(params[:id]) 
  @author = Author.includes(:user).find(params[:id])
   @user = @author.user
   @users = User.new
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy

  flash.notice = "Author Deleted"

  redirect_to  action: "index"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def author_params
      params.require(:author).permit(:username, :email, :password, :password_confirmation)
    end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
def show
	@tag = Tag.find(params[:id])

end
def index
	@tags = Tag.all
end
def destroy
	@tag = Tag.find(params[:id])
	@tag.destroy
	@tags = Tag.all 
end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	 before_action :require_login, except: [:index]
	 before_action :require_owner, only: :edit
def require_owner
	if current_user != Author.includes(:user).find(params[:id])
    redirect_to root_path
    flash.notice = "You Cannot Edit This Profile"
    
  	end
end
def create
	@user = User.new(user_params)
	@user.author_id = params[:author_id]
	@user.save

	redirect_to root_path
end
def edit
	 @author = Author.includes(:user).find(params[:id])
	@user = @author.user
	
end
def update
	@user = User.find(params[:id])
	@user.author_id = params[:author_id]
	@user.update(user_params)

	flash.notice = "Your Profile has Been Updated"

   redirect_to author_path(@user)
end
def index
	@user = User.find(params[:author_id])
end

def user_params
	params.require(:user).permit(:body)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def gravatar_url(email, size)
    	gravatar = Digest::MD5::hexdigest(email).downcase
    	url = "http://gravatar.com/avatar/#{gravatar}.png?s=#{size}"
  	end

end

app/helpers/articles_helper.rb
module ArticlesHelper
def article_params
	params.require(:article).permit(:title, :body, :tag_list, :category_id, :author_id)
end
end

app/helpers/authors_helper.rb
module AuthorsHelper

def name_for(author)
	author.user.body if author.user.present?
end

end

app/helpers/categories_helper.rb
module CategoriesHelper
def category_params
	params.require(:category).permit(:name)
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta property="og:image" content='<%= image_url "og.jpg" %>'/>
    <%= display_meta_tags og: {title: :title, description: :description, url: :url} %>
        <%= display_meta_tags site: 'www.jogooletters.com' %>
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
     
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
         
  </head>

<body class="layout-two-column-left" >

<div class="capsule">
    <div id="main">
          <div class='image_top'> <a href="/authors/1"> <%= image_tag "air-mail1.jpg", id: 'image_top'%> </a><br> <p class="about">ABOUT</p></div>
          
        <div id="top-nav">
           <div class="blogname">
            <a href="/">
            <h1>Jogoo letters</h1>
            <h5 id="catch">My Head in my Fingers</h5>
            </a>
          </div>
          <ul>
            <li>
              <%= link_to "Home", root_path %>  
              <%= link_to "Posts", articles_path %>
              <%= link_to "Tags", tags_path %>
              <a href="/authors/1"> About </a>
              <% if current_user.try(:admin?) %>
                <%= link_to "Authors", authors_path %>
              <% end %>

              </li>
           </ul>

         </div>
            <br class="clear"> 
             <div class="container">
             <p class="flash"><%= flash.notice %></p>
              <div class="content"> 
                <%= yield %>

              </div>
            </div>
            <br class="clear">
            
    </div>
</div>
<div class="footer">

      <hr style="margin: 0;">
        <div class="follow-buttons">
          <p>Follow us:</p>
          <div style="clear: both; overflow: hidden;">
            <div class="fb-follow"> <iframe src="https://www.facebook.com/plugins/follow.php?href=https%3A%2F%2Fwww.facebook.com%2Fkenny.m.mugambi&width=78px&height=28&layout=button&size=large&show_faces=true&appId" width="78px" height="28" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe></div>
            <div class="twitter-follow"><a href="https://twitter.com/Jogoo_Letters?ref_src=twsrc%5Etfw" data-button = "grey" class="twitter-follow-button" data-size="large" data-show-screen-name="false" data-show-count="false" style="padding-top: 10px;">Follow @Jogoo_Letters</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script></div>
          </div>

          <div><h6>
              <% if logged_in? %>
                <%= "Logged in as #{current_user.email}" %>
                <%= link_to "(logout)", logout_path %>
                <% end %>
            </h6>
          </div>
        </div>
        <br clear="both">
</div>
<script language="javascript" type="text/javascript">
     $(window).load(function() {
     $('#loading').hide();
  });
</script>

</body>
</html>